---
name: Build Karpenter Controller image

on:
  workflow_dispatch:
  push:

jobs:
  build-image:
    name: Build Controller Image
    runs-on: ubuntu-latest
    env:
      KO_DOCKER_REPO: ${{ secrets.REGISTRY_URL }}
      SOURCE_DATE_EPOCH:
      KO_DATA_DATE_EPOCH:

    steps:
      - uses: actions/checkout@v4.1.7
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'

      - uses: ko-build/setup-ko@v0.8
      - run: ko publish -B --platform all --sbom none -t $(echo "${GITHUB_SHA}" | cut -c1-8) x./cmd/controller
